import './globals.css'

export const metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex justify-center mt-10'>{children}</body>
    </html>
  )
}
